version: '3.8'

services:
  crewai-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - SERPER_API_KEY=${SERPER_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./output:/app/output
      - ./temp:/app/temp
      - ./.env:/app/.env:ro
      # Montar código fuente para desarrollo (los cambios se reflejan sin rebuild)
      - ./tools:/app/tools
      - ./agents:/app/agents
      - ./flows:/app/flows
      - ./utils:/app/utils
      - ./app.py:/app/app.py
    restart: unless-stopped
    networks:
      - crewai-network

networks:
  crewai-network:
    driver: bridge
